// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXHK-doLPskHSKqrAQXcBQ-hujKFqHJp0',
    appId: '1:1035406410766:web:81e253b6c325213328e85f',
    messagingSenderId: '1035406410766',
    projectId: 'insides-367717',
    authDomain: 'insides-367717.firebaseapp.com',
    storageBucket: 'insides-367717.appspot.com',
    measurementId: 'G-HSMWEQBCHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXosLZVDMnY20VBIYus2jfo4oC98kJVeI',
    appId: '1:1035406410766:android:2776801c035f877228e85f',
    messagingSenderId: '1035406410766',
    projectId: 'insides-367717',
    storageBucket: 'insides-367717.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlEymfHuaGxgEDHiCTSzhn3hK3bhmYPAM',
    appId: '1:1035406410766:ios:67a29b55ad1cc49628e85f',
    messagingSenderId: '1035406410766',
    projectId: 'insides-367717',
    storageBucket: 'insides-367717.appspot.com',
    androidClientId:
        '1035406410766-8kfdt3rptgnvv07lnb79ps5ailivjgbu.apps.googleusercontent.com',
    iosClientId:
        '1035406410766-b43123ipuu5v2dc6dkkav2mgi6eal44h.apps.googleusercontent.com',
    iosBundleId: 'com.example.insides',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlEymfHuaGxgEDHiCTSzhn3hK3bhmYPAM',
    appId: '1:1035406410766:ios:67a29b55ad1cc49628e85f',
    messagingSenderId: '1035406410766',
    projectId: 'insides-367717',
    storageBucket: 'insides-367717.appspot.com',
    androidClientId:
        '1035406410766-8kfdt3rptgnvv07lnb79ps5ailivjgbu.apps.googleusercontent.com',
    iosClientId:
        '1035406410766-b43123ipuu5v2dc6dkkav2mgi6eal44h.apps.googleusercontent.com',
    iosBundleId: 'com.example.insides',
  );
}
